version: '3.8'

services:
    web:
        image: next-with-docker-dev
        build:
            context: .
        volumes:
            - .:/app
        ports:
            - 3000:3000
        environment:
            NODE_ENV: development
